- name: Build
  hosts: localhost
  connection: local

  tasks:
    - name: ensure workspace/branch dir exists
      file: path={{ workspace }}/{{branch}} state=directory
    - name: Clone or update Cosnics repo
      git: repo={{ repo }} dest={{ workspace }}/{{branch}} version={{ branch }} force=yes
    - name: Composer update
      composer:
        command: update
        working_dir: "{{ workspace }}/{{branch}}"